version: '3.7'

x-build-args: &build-args
  args:
    - USER=${USER}


networks:
  default:
    driver: bridge
  traefik-net:
    name: traefik_net
    external: true

volumes:
  mysql_data: {}

services:
  nginx:
    container_name: "${PROJECT_NAME}-nginx"
    image: nginx:mainline-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./:/srv/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-nginx.rule=Host(`${PROJECT_HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}-nginx.entrypoints=web"
      - "traefik.docker.network=traefik_net"
    networks:
      - default
      - traefik-net

  php:
    container_name: "${PROJECT_NAME}-php"
    build:
      <<: *build-args
      context: ./docker/php-fpm
    volumes:
      - ./:/srv/app
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - default
    labels:
      - "traefik.enable=false"

  mysql:
    container_name: "${PROJECT_NAME}-mysql"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_LOCALHOST_PORT}:${DB_PORT}"
    networks:
      - default
    labels:
      - "traefik.enable=false"

  phpmyadmin:
    container_name: "${PROJECT_NAME}-pma"
    image: phpmyadmin:5.2
    depends_on:
      - mysql
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_ARBITRARY: 1
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
      PMA_ABSOLUTE_URI: "http://${PHPMYADMIN_HOST}/"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.${PROJECT_NAME}-pma.rule=Host(`${PHPMYADMIN_HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}-pma.entrypoints=web"
    networks:
      - default
      - traefik-net
